name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 24.7.0
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm clean-package -- devDependencies scripts packageManager
      - run: npm i -g npm@latest
      - run: npm publish --access public
