name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
        with:
          runtime: node@v26.5.1
      - run: pnpm build
      - name: Ensure clean working tree
        run: git --no-pager diff --exit-code
      - run: pnpm clean-package -- devDependencies scripts packageManager
      - run: pnpm stage publish --access public --provenance --no-git-checks
